-- ═══════════════════════════════════════════════════════════════════════════
-- 007 — Rental orders & line items  (the core lifecycle entity)
-- ───────────────────────────────────────────────────────────────────────────
-- A rental_order is one customer renting (or purchasing) one or more pieces of
-- equipment, delivered to a service address, billed monthly from delivery until
-- pickup completes. Each order has many line items; a line item may be bound to
-- a specific serialized equipment_unit.
--
-- RELIABILITY CORNERSTONE — no double-booking of a physical unit:
--   uq_line_item_active_unit is a PARTIAL UNIQUE index guaranteeing that any
--   given equipment_unit_id appears in AT MOST ONE active line item. Combined
--   with the advisory-lock reserve RPC (012), two staff cannot allocate the
--   same physical wheelchair/bed/etc. to overlapping rentals — the second write
--   fails at the database level, not just in the UI.
--
-- Status lifecycle (order-level), from the dashboard/rentals designs:
--   open → pending → scheduled → delivered → active → (overdue) →
--   pickup_scheduled → closed   (or cancelled at any point)
--
-- Idempotent: CREATE TABLE/INDEX IF NOT EXISTS, DROP-then-CREATE policies.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── Orders ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.rental_orders (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_no       BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,  -- human-friendly ref
  customer_id    UUID NOT NULL REFERENCES public.customers(id) ON DELETE RESTRICT,
  order_type     TEXT NOT NULL DEFAULT 'rental' CHECK (order_type IN ('rental', 'purchase')),
  status         TEXT NOT NULL DEFAULT 'open' CHECK (status IN
                   ('open', 'pending', 'scheduled', 'delivered', 'active',
                    'overdue', 'pickup_scheduled', 'closed', 'cancelled')),
  -- Service / delivery address (snapshotted from the customer at order time).
  address_line1  TEXT,
  address_city   TEXT,
  address_state  TEXT DEFAULT 'NY',
  address_zip    TEXT,
  start_date     DATE,             -- rental start (delivery date)
  end_date       DATE,             -- pickup/return date; NULL while out
  monthly_rate   NUMERIC(10,2) CHECK (monthly_rate >= 0),   -- snapshot sum of rental lines
  deposit_amount NUMERIC(10,2) CHECK (deposit_amount >= 0),
  special_notes  TEXT,
  created_by     UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_rental_orders_customer ON public.rental_orders (customer_id);
CREATE INDEX IF NOT EXISTS idx_rental_orders_status   ON public.rental_orders (status);
CREATE INDEX IF NOT EXISTS idx_rental_orders_start    ON public.rental_orders (start_date);

-- ── Line items ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.rental_line_items (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id          UUID NOT NULL REFERENCES public.rental_orders(id) ON DELETE CASCADE,
  equipment_item_id UUID NOT NULL REFERENCES public.equipment_items(id) ON DELETE RESTRICT,
  -- The specific serialized unit allocated to this line (NULL for bulk supplies
  -- or before allocation).
  equipment_unit_id UUID REFERENCES public.equipment_units(id) ON DELETE RESTRICT,
  line_type         TEXT NOT NULL DEFAULT 'rental' CHECK (line_type IN ('rental', 'purchase')),
  quantity          INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
  monthly_rate      NUMERIC(10,2) CHECK (monthly_rate >= 0),  -- snapshot
  sale_price        NUMERIC(10,2) CHECK (sale_price >= 0),     -- snapshot (purchases)
  -- TRUE while this allocation holds the unit (delivered/out). Set FALSE on
  -- return so the unit frees up. The partial unique index keys off this.
  is_active         BOOLEAN NOT NULL DEFAULT TRUE,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_line_items_order ON public.rental_line_items (order_id);
CREATE INDEX IF NOT EXISTS idx_line_items_item  ON public.rental_line_items (equipment_item_id);
CREATE INDEX IF NOT EXISTS idx_line_items_unit  ON public.rental_line_items (equipment_unit_id);

-- *** The double-booking backstop ***
-- A serialized unit can be in at most ONE active line item at a time.
CREATE UNIQUE INDEX IF NOT EXISTS uq_line_item_active_unit
  ON public.rental_line_items (equipment_unit_id)
  WHERE is_active AND equipment_unit_id IS NOT NULL;

-- ── RLS ────────────────────────────────────────────────────────────────────
ALTER TABLE public.rental_orders     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rental_line_items ENABLE ROW LEVEL SECURITY;

-- Staff & admin: full access to orders and line items.
DROP POLICY IF EXISTS "rental_orders_all_staff" ON public.rental_orders;
CREATE POLICY "rental_orders_all_staff" ON public.rental_orders
  FOR ALL USING (public.is_staff_or_admin()) WITH CHECK (public.is_staff_or_admin());

DROP POLICY IF EXISTS "rental_line_items_all_staff" ON public.rental_line_items;
CREATE POLICY "rental_line_items_all_staff" ON public.rental_line_items
  FOR ALL USING (public.is_staff_or_admin()) WITH CHECK (public.is_staff_or_admin());

-- Driver SELECT access (scoped to orders with a delivery assigned to them) is
-- added in 008_deliveries.sql, once the deliveries join exists.

DROP TRIGGER IF EXISTS set_updated_at ON public.rental_orders;
CREATE TRIGGER set_updated_at
  BEFORE UPDATE ON public.rental_orders
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS set_updated_at ON public.rental_line_items;
CREATE TRIGGER set_updated_at
  BEFORE UPDATE ON public.rental_line_items
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
