-- ═══════════════════════════════════════════════════════════════════════════
-- catalog_import.sql — REAL equipment catalog imported from Shopify (READ-ONLY pull)
-- ───────────────────────────────────────────────────────────────────────────
-- Source: cottage-pharmacy-surgical.myshopify.com, 14 products.
-- Mapping: Shopify price = monthly rental rate (variants = rental term; 'month'
--   variant preferred); category derived from tags/name; qty = summed inventory;
--   description = stripped body_html; image_url = first product image; SKUs are
--   generated (Shopify has none); shopify_product_id links back for re-sync.
-- NO sale price in Shopify for these rental items -> sale_price left NULL.
--
-- Idempotent: upsert on shopify_product_id; units created once per asset_tag.
-- Run on demand AFTER migrations 001-014:
--   python3 scripts/run_migrations.py --only catalog_import.sql
-- Requires migration 014 (shopify_product_id, vendor columns).
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO public.equipment_items
  (name, description, category, sku, image_url, monthly_rental_price,
   quantity_on_hand, is_serialized, is_rentable, is_purchasable, vendor, shopify_product_id)
VALUES
  ('3 Position Seat Lift Chair', 'Delivers 3-position and infinite position seat lift chairs, also known as medical recliners, for short-term and long-term rental needs.', 'seating', '3PSL', 'https://cdn.shopify.com/s/files/1/0083/8687/1358/products/71PAW-IkmML._SX522.jpg?v=1550251686', 250.00, 1, TRUE, TRUE, FALSE, 'Cottage Pharmacy & Surgicals', 2019018047550),
  ('5 Liter Compact Stationary Oxygen Concentrator', '5 Liter Concentrator Oxygen Sensor It is the most reliable, efficient, and convenient source of supplemental oxygen available. The oxygen concentrator is 34% smaller than other traditional 5 liter units and is electrically operated. This unit separates the oxygen from the air in the room allowing high-purity oxygen to be delivered through the oxygen outlet. Even though the compact concentrator filters oxygen in the room, it will not affect the normal level of oxygen throughout the room. Stationary must be plugged in to use. Oxygen concentrating effectiveness: 1-5 lpm@93%02 (+/-3%). Use with a maximum of 50'' of tubing when using a 7'' foot cannula and bubble humidifier.', 'respiratory', '5LCS', 'https://cdn.shopify.com/s/files/1/0083/8687/1358/products/devilbiss-oxygen-concentrator-5-liter-d54.png?v=1550251699', 299.00, 4, TRUE, TRUE, FALSE, 'Cottage Pharmacy & Surgicals', 2019018571838),
  ('COMPANION WHEELCHAIR', NULL, 'mobility', 'CW', 'https://cdn.shopify.com/s/files/1/0083/8687/1358/products/f9e676d2-a92a-42ec-a1ce-238fbc831e12._CR0_0_300_300_PT0_SX300__-Copy.jpg?v=1635358384', 199.99, 5, TRUE, TRUE, FALSE, 'Cottage Pharmacy & Surgical', 7036766290093),
  ('Companion wheelchair - Lightweight Transport Adult Folding Wheelchair with Handbrakes', 'Transport wheelchair has large 12 inch rear wheels for better performance on uneven outdoor surfaces | Loop-style manual handbrakes are ideal for locking the rear wheels during transfers Powder coated aluminum ultralight frame is durable and has a weight capacity of 300 lbs The portable back is collapsible (folds down) for easy storage, transport, and travel Full-length permanent armrest, Detachable footrests, Seat belt for safety, Comfortable nylon upholstery Seat dimensions are 18 x 16 inches', 'mobility', 'CWLT', 'https://cdn.shopify.com/s/files/1/0083/8687/1358/products/81a0zDPEA2L._SX522.jpg?v=1550251693', 50.00, 4, TRUE, TRUE, FALSE, 'PYK Local', 2019018276926),
  ('Freestyle Portable Oxygen Concentrator', 'Its only 6.7 pounds, the FreeStyle portable oxygen machine is compact, stylish, and convenient to carry with you, wherever you go. It delivers pulse flow only oxygen from 1 to 5 settings for those with COPD who wish to continue traveling, working, and socializing as usual. With its fresh new design and a simple one-touch operation, the new and improved FreeStyle is the perfect pulse flow portable oxygen concentrator for people on the move. Your oxygen prescription doesn’t have to limit the activities that you love.', 'respiratory', 'FPOC', 'https://cdn.shopify.com/s/files/1/0083/8687/1358/products/Freestyle_5_Portable_Oxygen_Concentrator__57286.1510969246.1280.1280.jpg?v=1550251702', 500.00, 4, TRUE, TRUE, FALSE, 'Cottage Pharmacy & Surgicals', 2019018637374),
  ('Hip Chair', 'Heavy-gauge two-piece square steel tubing provides maximum support Mounts easily to metal frame headboards and fits most major manufacturers'' Attractive brown-vein finish Easy-to-install without tools Easy-to-adjust height, length and horizontal position', 'seating', 'HC', 'https://cdn.shopify.com/s/files/1/0083/8687/1358/products/17100-BV_7.jpg?v=1550251708', 200.00, 4, TRUE, TRUE, FALSE, 'Cottage Pharmacy & Surgicals', 2019018801214),
  ('Hospital Bed', NULL, 'bedroom', 'HB', 'https://cdn.shopify.com/s/files/1/0083/8687/1358/products/bed.jpg?v=1550251687', 200.00, 10, TRUE, TRUE, FALSE, 'Cottage Pharmacy & Surgicals', 2019018080318),
  ('Hoyer lift - Hydraulic Standard Patient Lift With Six Point Cradle', 'Standard Patient Lift has 6 Point Cradle and can use 4 or 6 point slings. Lift has 400-lb lifting capacity. Quick delivery. Use slings with straps. 400 lb capacity. Sling Sold Separately', 'mobility', 'HLHS', 'https://cdn.shopify.com/s/files/1/0083/8687/1358/products/l-hydraulic-patient-lift-with-six-point-cradle-and-5-casters-8345-5040.jpg?v=1550251689', 150.00, 5, TRUE, TRUE, FALSE, 'PYK Local', 2019018178622),
  ('Knee Scooter - Dual Pad Steerable Knee Walker with Basket, Alternative to Crutches', 'Ideal for individuals recovering from foot surgery, breaks, sprains, amputation, and ulcers of the foot Knee walker can be steered for increased maneuverability. Durable, steel frame with silver vein finish; Comes with a removable front basket Do not operate on inclines above 15 degrees slight incline. Do not travel over drops or barriers such as curbs or parking stops Deluxe braking system for increased safety. Weight Limit is 350 pounds', 'mobility', 'KSDP', 'https://cdn.shopify.com/s/files/1/0083/8687/1358/products/Knee_Scooter.jpg?v=1550251688', 50.00, 0, TRUE, TRUE, FALSE, 'PYK Local', 2019018145854),
  ('Non-Tilt Over bed Table', '38cm x 80cm table top is locked securely when height adjustment handle is released n5.1cm swivel casters allow for easy maneuverability; 2 Locking Casters provide stability nBase Dimensions: 15.5 D x 70cm W nTable top can be raised or lowered in infinite positions between 70cm - 110cm.', 'bedroom', 'NTOB', 'https://cdn.shopify.com/s/files/1/0083/8687/1358/products/over_the_bed_table.jpg?v=1550251698', 35.00, 4, TRUE, TRUE, FALSE, 'Cottage Pharmacy & Surgicals', 2019018539070),
  ('Reclining Wheelchair', 'Hydraulic reclining mechanism allows for infinite adjustments up to 180-degrees; Arms have support extension for reclining position Nylon upholstery is comfortable, lightweight, and easy to clean; Carbon Steel frame with silver vein finish is attractive and easy to maintain Composite Mag-style wheels are lightweight and maintenance free; Precision sealed wheel bearings in front and rear ensure long lasting performance and reliability; Wheels set back on frame prevents tipping', 'mobility', 'RW', 'https://cdn.shopify.com/s/files/1/0083/8687/1358/products/81N3BtoQG4L._SX522.jpg?v=1550251695', 75.00, 2, TRUE, TRUE, FALSE, 'PYK Local', 2019018407998),
  ('Suction Machine - Assist Suction Aspirator', 'Suction Aspirator is simple to use and has rugged construction to withstand the rigors of homecare use. It is also great for the crash cart. Vac-Assist Suction Aspirator features heavy-duty handle design that prevents breakage, heavy-duty vacuum regulator and ultra-quiet motor (only 58 decibel operation noise level). The solid base is easy to keep clean and features suction cup to keep the unit stationary while in use.', 'respiratory', 'SMAS', 'https://cdn.shopify.com/s/files/1/0083/8687/1358/products/suction_machine.jpg?v=1550251696', 200.00, 9, TRUE, TRUE, FALSE, 'PYK Local', 2019018440766),
  ('Trapeze Bar', 'Heavy-gauge two-piece square steel tubing provides maximum support Mounts easily to metal frame headboards and fits most major manufacturers'' Attractive brown-vein finish Easy-to-install without tools Easy-to-adjust height, length and horizontal position', 'bedroom', 'TB', 'https://cdn.shopify.com/s/files/1/0083/8687/1358/products/13009KT-BV_4.jpg?v=1550251705', 125.00, 10, TRUE, TRUE, FALSE, 'Cottage Pharmacy & Surgicals', 2019018768446),
  ('Wheelchair - Light Weight Wheelchair with Various Flip Back Arm Styles and Front Rigging Options', 'Carbon steel frame with silver vein finish; Nylon upholstery is durable, lightweight, attractive, and easy to clean; Weighs under 36 lbs (excluding front riggings) Built-in seat rail extensions and extendable upholstery easily adjust seat depth from 16" to 18"; Padded armrests provide additional comfort Composite, Mag-style wheels are lightweight and maintenance free; 8" front casters are adjustable in three positions New frame style eliminates seat guides and allows for custom back inserts and accessories; Dual axle provides easy transition of seat height to hemi-level Precision sealed wheel bearings in front and rear ensure long-lasting performance and reliability; Comes with push-to-lock wheel locks', 'mobility', 'WLWW', 'https://cdn.shopify.com/s/files/1/0083/8687/1358/products/91xNn9rThxL._SX522.jpg?v=1550251694', 299.99, 5, TRUE, TRUE, FALSE, 'PYK Local', 2019018309694)
ON CONFLICT (shopify_product_id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  image_url = EXCLUDED.image_url,
  monthly_rental_price = EXCLUDED.monthly_rental_price,
  vendor = EXCLUDED.vendor;

-- Generate serialized units to match on-hand quantity (idempotent via asset_tag).
INSERT INTO public.equipment_units (item_id, asset_tag, status)
SELECT i.id, i.sku || '-' || g, 'available'
FROM public.equipment_items i
CROSS JOIN LATERAL generate_series(1, i.quantity_on_hand) g
WHERE i.shopify_product_id IS NOT NULL
ON CONFLICT (asset_tag) DO NOTHING;
